export const hotelsData = [
  {
    id: 1,
    name: "Al-Refaa Ri’a Bakhsh Hotel",
    arabicName: "فندق الرفاع ريع بخش",
    image: "/hotel/hotel1.jpg",
    price: 250,
    rating: 3.9,
    reviews: 9,
    location: "Makkah, Saudi Arabia",
    rooms: 33,
    propertyView: "fullKaaba",
    guestRating: "excellent",
    roomTypes: ["deluxe", "double", "familySuite"],
  },
  {
    id: 2,
    name: "Al-Refaa Al-Sadd Hotel",
    arabicName: "فندق الرفاع السد",
    image: "/hotel/hotel2.jpeg",
    price: 290,
    rating: 1.8,
    reviews: 120,
    location: "Makkah, Saudi Arabia",
    rooms: 45,
    propertyView: "partialKaaba",
    guestRating: "veryGood",
    roomTypes: ["double", "quadruple", "juniorSuite"],
  },
  {
    id: 3,
    name: "Karam Al-Refaa Hotel",
    arabicName: "سويس أوتيل مكة",
    image: "/hotel/hotel3.jpeg",
    price: 190,
    rating: 2.6,
    reviews: 98,
    location: "Makkah, Saudi Arabia",
    rooms: 40,
    propertyView: "noView",
    guestRating: "good",
    roomTypes: ["deluxe", "triple", "standard"],
  },
  {
    id: 4,
    name: "Barkat Al-Refaa Hotel",
    arabicName: "فندق بركة الرفاع",
    image: "/hotel/hotel4.jpeg",
    price: 224,
    rating: 3.6,
    reviews: 98,
    location: "Makkah, Saudi Arabia",
    rooms: 40,
    propertyView: "partialKaaba",
    guestRating: "veryGood",
    roomTypes: ["double", "quadruple", "juniorSuite"],
  },
  {
    id: 5,
    name: "Nasmah Al-Khaiir Hotel",
    arabicName: "فندق نسمات الخير",
    image: "/hotel/hotel5.jpeg",
    price: 184,
    rating: 5.0,
    reviews: 98,
    location: "Makkah, Saudi Arabia",
    rooms: 40,
    propertyView: "noView",
    guestRating: "good",
    roomTypes: ["familySuite", "hexagonal", "superDeluxe"],
  },
  {
    id: 6,
    name: "Al-Fajr Al-Badee 1",
    arabicName: "الفجر البديع 1",
    image: "/hotel/hotel6.jpeg",
    price: 204,
    rating: 4.6,
    reviews: 98,
    location: "Makkah, Saudi Arabia",
    rooms: 40,
    propertyView: "fullKaaba",
    guestRating: "excellent",
    roomTypes: ["deluxe", "juniorSuite", "standard"],
  },
  {
    id: 7,
    name: "Al-Refaa Ri'a Baksh Hotel",
    arabicName: "فندق الرفاع ريع بخش",
    image: "/hotel/hotel7.jpeg",
    price: 180,
    rating: 3.3,
    reviews: 98,
    location: "Makkah, Saudi Arabia",
    rooms: 40,
    propertyView: "noView",
    guestRating: "average",
    roomTypes: ["triple", "quadruple", "familySuite"],
  },
  {
    id: 8,
    name: "Rawaabi Al-Salam Hotel",
    arabicName: "فندق روابي السلام",
    image: "/hotel/hotel8.jpeg",
    price: 154,
    rating: 2.2,
    reviews: 98,
    location: "Makkah, Saudi Arabia",
    rooms: 40,
    propertyView: "partialKaaba",
    guestRating: "veryGood",
    roomTypes: ["deluxe", "double", "juniorSuite"],
  },
  {
    id: 9,
    name: "Vivian Al-Jameeza Hotel",
    arabicName: "فندق فيفيان الجمزة",
    image: "/hotel/hotel9.jpeg",
    price: 150,
    rating: 2.6,
    reviews: 98,
    location: "Makkah, Saudi Arabia",
    rooms: 40,
    propertyView: "fullKaaba",
    guestRating: "excellent",
    roomTypes: ["superDeluxe", "seniorSuite", "deluxe"],
  },
  {
    id: 10,
    name: "Vivian Al-Maabda Hotel",
    arabicName: "فندق فيفيان المعابدة",
    image: "/hotel/hotel10.jpeg",
    price: 142,
    rating: 3.6,
    reviews: 98,
    location: "Makkah, Saudi Arabia",
    rooms: 40,
    propertyView: "noView",
    guestRating: "good",
    roomTypes: ["double", "quadruple", "juniorSuite"],
  },
  {
    id: 11,
    name: "Al-Rafa Al-Aziza Hotel",
    arabicName: "فندق الرفاع الأزيزة",
    image: "/hotel/hotel11.jpeg",
    price: 160,
    rating: 2.6,
    reviews: 98,
    location: "Makkah, Saudi Arabia",
    rooms: 40,
    propertyView: "partialKaaba",
    guestRating: "veryGood",
    roomTypes: ["familySuite", "juniorSuite", "deluxe"],
  },
  {
    id: 12,
    name: "Wahet Al-Refaa Hotel",
    arabicName: "فندق واهت الرفاع",
    image: "/hotel/hotel12.jpeg",
    price: 170,
    rating: 4.1,
    reviews: 98,
    location: "Makkah, Saudi Arabia",
    rooms: 40,
    propertyView: "noView",
    guestRating: "average",
    roomTypes: ["triple", "double", "hexagonal"],
  },
  {
    id: 13,
    name: "Vivian Al-Aziza Hotel",
    arabicName: "فندق فيفيان العزيزية",
    image: "/hotel/hotel13.jpeg",
    price: 152,
    rating: 2.1,
    reviews: 98,
    location: "Makkah, Saudi Arabia",
    rooms: 40,
    propertyView: "fullKaaba",
    guestRating: "excellent",
    roomTypes: ["deluxe", "double", "juniorSuite"],
  },
  {
    id: 14,
    name: "Tariq Alhajrih Hotel",
    arabicName: "فندق تريق الحجريه",
    image: "/hotel/hotel14.jpeg",
    price: 232,
    rating: 4.0,
    reviews: 98,
    location: "Makkah, Saudi Arabia",
    rooms: 40,
    propertyView: "partialKaaba",
    guestRating: "veryGood",
    roomTypes: ["familySuite", "quadruple", "juniorSuite"],
  },
];
